import React, { useState, useEffect, useRef } from 'react';
import { View, Text, FlatList, TouchableOpacity, StyleSheet, Alert, TextInput } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { FirebaseRecaptchaVerifierModal } from 'expo-firebase-recaptcha';
import { PhoneAuthProvider, signInWithCredential, onAuthStateChanged } from 'firebase/auth';
import { auth, getCafes, placeOrder } from './firebase';
const COFFEE='#6f4e37', CREAM='#faf6f1';
const demoCafes=[{id:'c0',name:'مقهى الروضة',rating:4.8,time:'20 دقيقة',dist:'1.2 كم',tag:'قهوة مختصة',menu:[{name:'إسبريسو',price:12},{name:'كابتشينو',price:16},{name:'سبانيش لاتيه',price:20},{name:'كرواسون زبدة',price:10}]},{id:'c1',name:'بُن الديرة',rating:4.6,time:'15 دقيقة',dist:'0.8 كم',tag:'قهوة عربية',menu:[{name:'قهوة عربية بالهيل',price:15},{name:'كرك عدني',price:8},{name:'تمر سكري',price:12},{name:'شاي مغربي',price:10}]},{id:'c2',name:'كوفي لايف',rating:4.7,time:'25 دقيقة',dist:'2.1 كم',tag:'مشروبات باردة',menu:[{name:'آيس لاتيه',price:18},{name:'فرابتشينو كراميل',price:22},{name:'كوكيز',price:9},{name:'ماتشا مثلجة',price:21}]}];
export const store={cart:{}};
function LoginScreen(){const[phone,setPhone]=useState(''),[code,setCode]=useState(''),[sent,setSent]=useState(false),recaptcha=useRef(null);const sendCode=async()=>{if(!phone.startsWith('+'))return Alert.alert('أدخل الرقم بصيغة دولية مثل +9665xxxxxxxx');try{const provider=new PhoneAuthProvider(auth);const verificationId=await provider.verifyPhoneNumber(phone,recaptcha.current);store.verificationId=verificationId;setSent(true)}catch(e){Alert.alert('خطأ',e.message)}};const verify=async()=>{try{const cred=PhoneAuthProvider.credential(store.verificationId,code);await signInWithCredential(auth,cred)}catch(e){Alert.alert('رمز غير صحيح')}};return <View style={s.screen}><FirebaseRecaptchaVerifierModal ref={recaptcha} firebaseConfig={require('./firebase').app.options}/><Text style={s.h1}>قهوتي ☕</Text><Text style={s.meta}>سجّل الدخول برقم جوالك</Text><TextInput style={s.input} dir="ltr" placeholder="+9665xxxxxxxx" value={phone} onChangeText={setPhone} keyboardType="phone-pad"/><TouchableOpacity style={s.btn} onPress={sendCode}><Text style={s.btnText}>إرسال الرمز</Text></TouchableOpacity>{sent&&<><TextInput style={s.input} dir="ltr" placeholder="رمز التحقق" value={code} onChangeText={setCode} keyboardType="number-pad"/><TouchableOpacity style={s.btn} onPress={verify}><Text style={s.btnText}>تأكيد الدخول</Text></TouchableOpacity></>}</View>}
function HomeScreen({navigation}){const[cafes,setCafes]=useState(store.cafes||[]);useEffect(()=>{getCafes().then(setCafes).catch(()=>setCafes(demoCafes))},[]);store.cafes=cafes;return <View style={s.screen}><Text style={s.h1}>مقاهي قريبة منك</Text><FlatList data={cafes} keyExtractor={c=>String(c.id)} renderItem={({item})=><TouchableOpacity style={s.card} onPress={()=>navigation.navigate('Menu',{cafe:item})}><Text style={s.cardTitle}>{item.name}</Text><Text style={s.tag}>{item.tag}</Text><Text style={s.meta}>★ {item.rating} · {item.dist} · {item.time}</Text></TouchableOpacity>}/></View>}
function MenuScreen({route,navigation}){const{cafe}=route.params;const[,force]=useState(0);const add=(i,d)=>{const k=`${cafe.id}_${i}`;store.cart[k]=(store.cart[k]||0)+d;if(store.cart[k]<=0)delete store.cart[k];force(x=>x+1)};const count=Object.values(store.cart).reduce((a,b)=>a+b,0);return <View style={s.screen}><Text style={s.h1}>{cafe.name}</Text><FlatList data={cafe.menu} keyExtractor={m=>m.name} renderItem={({item,index})=><View style={s.row}><View style={{flex:1}}><Text style={s.cardTitle}>{item.name}</Text><Text style={s.meta}>{item.price} ر.س</Text></View>{store.cart[`${cafe.id}_${index}`]>0&&<TouchableOpacity style={s.btnSmall} onPress={()=>add(index,-1)}><Text style={s.btnText}>−</Text></TouchableOpacity>}<TouchableOpacity style={s.btnSmall} onPress={()=>add(index,1)}><Text style={s.btnText}>+</Text></TouchableOpacity></View>}/>{count>0&&<TouchableOpacity style={s.btn} onPress={()=>navigation.navigate('Cart')}><Text style={s.btnText}>عرض السلة ({count})</Text></TouchableOpacity>}</View>}
function CartScreen({user}){const cafes=store.cafes||[];const[,force]=useState(0),entries=Object.entries(store.cart);const total=entries.reduce((sum,[k,q])=>{const[c,i]=k.split('_'),cafe=cafes.find(x=>String(x.id)===c);return cafe?sum+cafe.menu[i].price*q:sum},0);const checkout=async()=>{const items=entries.map(([k,q])=>{const[c,i]=k.split('_'),cafe=cafes.find(x=>String(x.id)===c);return{cafeId:c,cafeName:cafe.name,item:cafe.menu[i].name,price:cafe.menu[i].price,qty:q}});try{const orderId=await placeOrder({userId:user.uid,phone:user.phoneNumber,items,total:total+8});store.cart={};force(x=>x+1);Alert.alert('تم استلام طلبك ✅',`رقم الطلب ${orderId.slice(0,6)} — الوقت المتوقع 25 دقيقة`)}catch(e){Alert.alert('تعذّر إرسال الطلب',e.message)}};return <View style={s.screen}><Text style={s.h1}>السلة</Text><FlatList data={entries} keyExtractor={([k])=>k} ListEmptyComponent={<Text style={s.meta}>السلة فارغة</Text>} renderItem={({item:[k,q]})=>{const[c,i]=k.split('_'),cafe=cafes.find(x=>String(x.id)===c);if(!cafe)return null;return <View style={s.row}><Text style={{flex:1}}>{cafe.menu[i].name} × {q}</Text><Text>{cafe.menu[i].price*q} ر.س</Text></View>}}/>{entries.length>0&&<><Text style={s.total}>الإجمالي مع التوصيل: {total+8} ر.س</Text><TouchableOpacity style={s.btn} onPress={checkout}><Text style={s.btnText}>إتمام الطلب</Text></TouchableOpacity></>}</View>}
const Stack=createNativeStackNavigator();export default function App(){const[user,setUser]=useState(null),[loading,setLoading]=useState(true);useEffect(()=>onAuthStateChanged(auth,u=>{setUser(u);setLoading(false)}),[]);if(loading)return <View style={s.screen}><Text style={s.meta}>جارٍ التحميل…</Text></View>;return <NavigationContainer><Stack.Navigator screenOptions={{headerTintColor:COFFEE,headerTitleAlign:'center'}}>{!user?<Stack.Screen name="Login" component={LoginScreen} options={{headerShown:false}}/>:<><Stack.Screen name="Home" component={HomeScreen} options={{title:'قهوتي ☕'}}/><Stack.Screen name="Menu" component={MenuScreen} options={({route})=>({title:route.params.cafe.name})}/><Stack.Screen name="Cart">{p=><CartScreen {...p} user={user}/>}</Stack.Screen></>}</Stack.Navigator></NavigationContainer>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:CREAM,padding:16,justifyContent:'center'},h1:{fontSize:22,fontWeight:'700',color:COFFEE,marginBottom:12,textAlign:'right'},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#ddd',borderRadius:12,padding:12,marginBottom:12,fontSize:16,textAlign:'left'},card:{backgroundColor:'#fff',borderRadius:12,padding:16,marginBottom:12,borderWidth:1,borderColor:'#ece5dd'},cardTitle:{fontSize:16,fontWeight:'600',textAlign:'right'},tag:{color:COFFEE,fontSize:12,marginTop:4,textAlign:'right'},meta:{color:'#8a7f78',fontSize:13,marginTop:4,textAlign:'right'},row:{flexDirection:'row',alignItems:'center',gap:8,backgroundColor:'#fff',borderRadius:12,padding:14,marginBottom:8,borderWidth:1,borderColor:'#ece5dd'},btnSmall:{backgroundColor:COFFEE,borderRadius:8,width:32,height:32,alignItems:'center',justifyContent:'center'},btn:{backgroundColor:COFFEE,borderRadius:12,padding:14,alignItems:'center',marginTop:8},btnText:{color:'#fff',fontSize:16,fontWeight:'600'},total:{fontWeight:'700',textAlign:'left',marginTop:8}});